trigger:
- main  # Change this to the branch you want to trigger the pipeline from

pool:
  vmImage: 'windows-latest'  # Use a Windows-based agent to run Windows Server-specific commands

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureConnection-ARM'  # Your Azure Service Connection name
    scriptType: 'pscore'  # Use PowerShell Core for Windows
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "Checking Azure Site Recovery Vault..."

      # Get Recovery Services Vault information with correct name and resource group
      $vault = az backup vault show --name DR1 --resource-group DR-RG --debug  # Added --debug for more details

      Write-Host "ASR Vault Info:"
      Write-Host $vault

      # If you want to list replicated items, you can run something like this:
      $replicatedItems = az backup item list --vault-name DR1 --resource-group DR-RG --query "[].{Name:name, Type:type, ProtectionStatus:properties.protectionStatus}" --debug  # Added --debug
      Write-Host "Replicated Items:"
      Write-Host $replicatedItems

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureConnection-ARM'  # Your Azure Service Connection name
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "Starting replication for Windows Server VM..."

      # Replace 'recoveryvm' with your actual VM name
      $vmName = "recoveryvm"  # This is where we define the VM name (no changes needed here)

      # Enable replication for the VM (replace with actual names and parameters)
      az recoveryservices replication protected-item enable --vault-name DR1 --resource-group DR-RG --item-name $vmName --source-resource-group DisasterRG --source-location EastUS --target-location WestUS --vm-name $vmName --debug  # Changed resource group to DisasterRG
      Write-Host "Replication started for $vmName"

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureConnection-ARM'  # Your Azure Service Connection name
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "Initiating a Test Failover for Windows Server VM..."

      # Use the same $vmName variable from previous task
      az recoveryservices replication failover --vault-name DR1 --resource-group DR-RG --item-name $vmName --failover-direction "Test" --debug  # Added --debug for more details
      Write-Host "Test Failover initiated for $vmName"
