trigger:
- main  # Change this to the branch you want to trigger the pipeline from

pool:
  vmImage: 'windows-latest'  # Use a Windows-based agent to run Windows Server-specific commands

steps:
# STEP 1: Enable Backup for the VM
- task: AzureCLI@2
  displayName: 'Enable Backup for Windows VM'
  inputs:
    azureSubscription: AzureConnection-ARM
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      Write-Host "Enabling Azure Backup for VM: recoveryvm"
      az backup protection enable-for-vm `
        --resource-group DR-RG `
        --vault-name DR1 `
        --vm recoveryvm `